# Generated by Django 4.0.4 on 2022-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='detalles',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
