# Generated by Django 4.0.4 on 2022-05-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_estudiante_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='detalles',
        ),
    ]
