# Generated by Django 4.0.4 on 2022-05-10 11:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0003_remove_estudiante_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tarjeta_presentacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
