# Generated by Django 4.0.4 on 2022-05-26 05:52

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_estudiante_informacion_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tiempo_de_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
